#version: "3.9"

services:
  audio2text:
    build: .
    container_name: audio2text
    volumes:
      - ./audios:/app/audios
      - ./outputs:/app/outputs
      - ./cache/ctranslate2:/root/.cache/ctranslate2
      - ./cache/huggingface:/root/.cache/huggingface
    working_dir: /app
    # Define el programa principal que se ejecutará siempre.
    # Los argumentos se pasarán desde el comando 'docker compose run'.
    entrypoint: [
        "python3", "transcribe.py",
    ]