#version: "3.9"

services:
  audio2text:
    build: .
    container_name: audio2text
    volumes:
      - ./audios:/app/audios
      - ./outputs:/app/outputs
      - ./cache/ctranslate2:/root/.cache/ctranslate2
      - ./cache/huggingface:/root/.cache/huggingface
    working_dir: /app
    command: [
        "python3", "transcribe.py",
        "-o", "outputs",
        "--language", "es",
        "-m", "small",
        "--compute-type", "int8",
        "--beam-size", "5",
        "--vad"
      ]